In [1]:
import pandas as pd

In [25]:
matches = pd.read_csv("matches.csv")
deliveries = pd.read_csv("deliveries.csv")

# Merge datasets
data = deliveries.merge(matches[['id','winner']], left_on='match_id', right_on='id')

In [26]:
data

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,id,winner
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN,335982,Kolkata Knight Riders
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,Kolkata Knight Riders
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN,335982,Kolkata Knight Riders
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,Kolkata Knight Riders
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,Kolkata Knight Riders
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,Kolkata Knight Riders
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,Kolkata Knight Riders
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,Kolkata Knight Riders
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,Kolkata Knight Riders
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,Kolkata Knight Riders

In [27]:
data['cumulative_runs'] = data.groupby('match_id')['total_runs'].cumsum()

In [28]:
data['cumulative_wickets'] = data.groupby('match_id')['is_wicket'].cumsum()

In [29]:
data['runs_left'] = data['total_runs'] - data['cumulative_runs']
data['balls_left'] = 120 - (data['over']*6 + data['ball'])
data['wickets_left'] = 10 - data['cumulative_wickets']

In [33]:
data.drop(columns=['extras_type','player_dismissed','dismissal_kind','fielder'],inplace=True)

In [34]:
data

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,is_wicket,id,winner,cumulative_runs,cumulative_wickets,runs_left,balls_left,wickets_left,crr,rrr
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,0,335982,Kolkata Knight Riders,1,0,0,119,10,6.000000,0.000000
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,0,335982,Kolkata Knight Riders,1,0,-1,118,10,3.000000,-0.050847
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,0,335982,Kolkata Knight Riders,2,0,-1,117,10,4.000000,-0.051282
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,0,335982,Kolkata Knight Riders,2,0,-2,116,10,3.000000,-0.103448
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,0,335982,Kolkata Knight Riders,2,0,-2,115,10,2.400000,-0.104348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,...,0,1426312,Kolkata Knight Riders,223,12,-222,61,-2,22.677966,-21.836066
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,...,0,1426312,Kolkata Knight Riders,224,12,-223,60,-2,22.400000,-22.300000
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,0,1426312,Kolkata Knight Riders,225,12,-224,59,-2,22.131148,-22.779661
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,0,1426312,Kolkata Knight Riders,226,12,-225,58,-2,21.870968,-23.275862
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,0,1426312,Kolkata Knight Riders,227,12,-226,57,-2,21.619048,-23.789474

In [35]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 22 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   match_id            260920 non-null  int64
 1   inning              260920 non-null  int64
 2   batting_team        260920 non-null  object
 3   bowling_team        260920 non-null  object
 4   over                260920 non-null  int64
 5   ball                260920 non-null  int64
 6   batter              260920 non-null  object
 7   bowler              260920 non-null  object
 8   non_striker         260920 non-null  object
 9   batsman_runs        260920 non-null  int64
 10  extra_runs          260920 non-null  int64
 11  total_runs          260920 non-null  int64
 12  is_wicket           260920 non-null  int64
 13  id                  260920 non-null  int64
 14  winner              260430 non-null  object
 15  cumulative_runs     260920 non-null  int64
 16  cumulative_wickets  260920 non-null  int64
 17  runs_left           260920 non-null  int64
 18  balls_left          260920 non-null  int64
 19  wickets_left        260920 non-null  int64
 20  crr                 260920 non-null  float64
 21  rrr                 260920 non-null  float64
dtypes: float64(2), int64(14), object(6)
memory usage: 43.8+ MB

In [36]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['batting_team'] = le.fit_transform(data['batting_team'])
data['bowling_team'] = le.fit_transform(data['bowling_team'])

In [37]:
data.drop(columns=['non_striker','bowler','batter'],inplace=True)

In [38]:
data['winner'].value_counts()

winner
Mumbai Indians                 34629
Chennai Super Kings            33388
Kolkata Knight Riders          30820
Royal Challengers Bangalore    27319
Rajasthan Royals               27029
Kings XI Punjab                20948
Sunrisers Hyderabad            20946
Delhi Daredevils               15709
Delhi Capitals                 11641
Deccan Chargers                 7013
Gujarat Titans                  6793
Lucknow Super Giants            5932
Punjab Kings                    5839
Gujarat Lions                   3063
Pune Warriors                   2883
Rising Pune Supergiant          2383
Royal Challengers Bengaluru     1668
Kochi Tuskers Kerala            1322
Rising Pune Supergiants         1105
Name: count, dtype: int64

In [39]:
data['winner']=le.fit(data['winner']).transform(data['winner'])

In [40]:
data['winner'].value_counts()

winner
10    34629
0     33388
8     30820
16    27319
13    27029
6     20948
18    20946
3     15709
2     11641
1      7013
5      6793
9      5932
12     5839
4      3063
11     2883
14     2383
17     1668
7      1322
15     1105
19      490
Name: count, dtype: int64

In [41]:
data

,match_id,inning,batting_team,bowling_team,over,ball,batsman_runs,extra_runs,total_runs,is_wicket,id,winner,cumulative_runs,cumulative_wickets,runs_left,balls_left,wickets_left,crr,rrr
0,335982,1,8,16,0,1,0,1,1,0,335982,8,1,0,0,119,10,6.000000,0.000000
1,335982,1,8,16,0,2,0,0,0,0,335982,8,1,0,-1,118,10,3.000000,-0.050847
2,335982,1,8,16,0,3,0,1,1,0,335982,8,2,0,-1,117,10,4.000000,-0.051282
3,335982,1,8,16,0,4,0,0,0,0,335982,8,2,0,-2,116,10,3.000000,-0.103448
4,335982,1,8,16,0,5,0,0,0,0,335982,8,2,0,-2,115,10,2.400000,-0.104348
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,8,18,9,5,1,0,1,0,1426312,8,223,12,-222,61,-2,22.677966,-21.836066
260916,1426312,2,8,18,9,6,1,0,1,0,1426312,8,224,12,-223,60,-2,22.400000,-22.300000
260917,1426312,2,8,18,10,1,1,0,1,0,1426312,8,225,12,-224,59,-2,22.131148,-22.779661
260918,1426312,2,8,18,10,2,1,0,1,0,1426312,8,226,12,-225,58,-2,21.870968,-23.275862
260919,1426312,2,8,18,10,3,1,0,1,0,1426312,8,227,12,-226,57,-2,21.619048,-23.789474

In [42]:
data.drop(columns=['id','crr','rrr','match_id'],inplace=True)

In [43]:
data

,inning,batting_team,bowling_team,over,ball,batsman_runs,extra_runs,total_runs,is_wicket,winner,cumulative_runs,cumulative_wickets,runs_left,balls_left,wickets_left
0,1,8,16,0,1,0,1,1,0,8,1,0,0,119,10
1,1,8,16,0,2,0,0,0,0,8,1,0,-1,118,10
2,1,8,16,0,3,0,1,1,0,8,2,0,-1,117,10
3,1,8,16,0,4,0,0,0,0,8,2,0,-2,116,10
4,1,8,16,0,5,0,0,0,0,8,2,0,-2,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,2,8,18,9,5,1,0,1,0,8,223,12,-222,61,-2
260916,2,8,18,9,6,1,0,1,0,8,224,12,-223,60,-2
260917,2,8,18,10,1,1,0,1,0,8,225,12,-224,59,-2
260918,2,8,18,10,2,1,0,1,0,8,226,12,-225,58,-2
260919,2,8,18,10,3,1,0,1,0,8,227,12,-226,57,-2

In [49]:
data['result'] = (data['batting_team'] == data['winner']).astype(int)

In [54]:
data

,inning,batting_team,bowling_team,over,ball,batsman_runs,extra_runs,total_runs,is_wicket,winner,cumulative_runs,cumulative_wickets,runs_left,balls_left,wickets_left,result
0,1,8,16,0,1,0,1,1,0,8,1,0,0,119,10,1
1,1,8,16,0,2,0,0,0,0,8,1,0,-1,118,10,1
2,1,8,16,0,3,0,1,1,0,8,2,0,-1,117,10,1
3,1,8,16,0,4,0,0,0,0,8,2,0,-2,116,10,1
4,1,8,16,0,5,0,0,0,0,8,2,0,-2,115,10,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,2,8,18,9,5,1,0,1,0,8,223,12,-222,61,-2,1
260916,2,8,18,9,6,1,0,1,0,8,224,12,-223,60,-2,1
260917,2,8,18,10,1,1,0,1,0,8,225,12,-224,59,-2,1
260918,2,8,18,10,2,1,0,1,0,8,226,12,-225,58,-2,1
260919,2,8,18,10,3,1,0,1,0,8,227,12,-226,57,-2,1

In [50]:
data.corr()

,inning,batting_team,bowling_team,over,ball,batsman_runs,extra_runs,total_runs,is_wicket,winner,cumulative_runs,cumulative_wickets,runs_left,balls_left,wickets_left,result
inning,1.000000,0.002311,-0.004092,-0.049785,-0.004786,-0.005690,0.000674,-0.005593,0.001028,-0.005259,0.822727,0.776090,-0.823675,0.049972,-0.776090,0.059566
batting_team,0.002311,1.000000,-0.099839,-0.001216,0.001203,0.001711,-0.000161,0.001690,0.002330,0.438940,0.004723,-0.002799,-0.004700,0.001150,0.002799,-0.020965
bowling_team,-0.004092,-0.099839,1.000000,-0.000197,0.000541,0.003976,0.001614,0.004349,-0.002134,0.461394,0.002647,-0.003611,-0.002579,0.000168,0.003611,0.017811
over,-0.049785,-0.001216,-0.000197,1.000000,-0.001241,0.080040,0.004437,0.081610,0.072963,-0.004559,0.431518,0.352969,-0.430634,-0.998587,-0.352969,-0.027663
ball,-0.004786,0.001203,0.000541,-0.001241,1.000000,0.004391,0.000176,0.004463,0.004258,0.000677,0.023096,0.017174,-0.023047,-0.051911,-0.017174,-0.001160
batsman_runs,-0.005690,0.001711,0.003976,0.080040,0.004391,1.000000,-0.142079,0.977934,-0.171751,0.002695,0.069936,-0.019956,-0.054029,-0.080165,0.019956,0.052849
extra_runs,0.000674,-0.000161,0.001614,0.004437,0.000176,-0.142079,1.000000,0.067852,-0.041903,-0.000244,0.006388,0.002305,-0.005286,-0.004441,-0.002305,0.005533
total_runs,-0.005593,0.001690,0.004349,0.081610,0.004463,0.977934,0.067852,1.000000,-0.181955,0.002665,0.071839,-0.019627,-0.055572,-0.081737,0.019627,0.054435
is_wicket,0.001028,0.002330,-0.002134,0.072963,0.004258,-0.171751,-0.041903,-0.181955,1.000000,-0.000551,0.037666,0.083404,-0.040678,-0.073091,-0.083404,-0.045553
winner,-0.005259,0.438940,0.461394,-0.004559,0.000677,0.002695,-0.000244,0.002665,-0.000551,1.000000,-0.003578,-0.005682,0.003625,0.004516,0.005682,-0.005107
cumulative_runs,0.822727,0.004723,0.002647,0.431518,0.023096,0.069936,0.006388,0.071839,0.037666,-0.003578,1.000000,0.761623,-0.999867,-0.432164,-0.761623,0.021010
cumulative_wickets,0.776090,-0.002799,-0.003611,0.352969,0.017174,-0.019956,0.002305,-0.019627,0.083404,-0.005682,0.761623,1.000000,-0.762737,-0.353406,-1.000000,-0.019444
runs_left,-0.823675,-0.004700,-0.002579,-0.430634,-0.023047,-0.054029,-0.005286,-0.055572,-0.040678,0.003625,-0.999867,-0.762737,1.000000,0.431279,0.762737,-0.020142
balls_left,0.049972,0.001150,0.000168,-0.998587,-0.051911,-0.080165,-0.004441,-0.081737,-0.073091,0.004516,-0.432164,-0.353406,0.431279,1.000000,0.353406,0.027687
wickets_left,-0.776090,0.002799,0.003611,-0.352969,-0.017174,0.019956,-0.002305,0.019627,-0.083404,0.005682,-0.761623,-1.000000,0.762737,0.353406,1.000000,0.019444
result,0.059566,-0.020965,0.017811,-0.027663,-0.001160,0.052849,0.005533,0.054435,-0.045553,-0.005107,0.021010,-0.019444,-0.020142,0.027687,0.019444,1.000000

In [60]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

X = data[['inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman_runs', 'extra_runs', 'total_runs', 'is_wicket',
       'cumulative_runs', 'cumulative_wickets', 'runs_left', 'balls_left',
       'wickets_left']]
y = data['result']

In [61]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# models
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier(),
    "Gradient Boosting": GradientBoostingClassifier(),
    "KNN": KNeighborsClassifier()
}

# training + evaluation
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    acc = accuracy_score(y_test, preds)
    print(f"{name}: {acc:.4f}")

Logistic Regression: 0.5653
Decision Tree: 0.8562
Random Forest: 0.8258
Gradient Boosting: 0.6559
KNN: 0.7227

In [63]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# features and target
X = data[['inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman_runs', 'extra_runs', 'total_runs', 'is_wicket',
       'cumulative_runs', 'cumulative_wickets', 'runs_left', 'balls_left',
       'wickets_left']]
y = data['result']

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# model
dt = DecisionTreeClassifier()

# train
dt.fit(X_train, y_train)

# predict
y_pred_dt = dt.predict(X_test)

# accuracy
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.8552621493177985

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# features and target
X = data[['inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman_runs', 'extra_runs', 'total_runs', 'is_wicket',
       'cumulative_runs', 'cumulative_wickets', 'runs_left', 'balls_left',
       'wickets_left']]
y = data['result']

# split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# model
rf = RandomForestClassifier()

# train
rf.fit(X_train, y_train)

# predict
y_pred_rf = rf.predict(X_test)

# accuracy
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))

Random Forest Accuracy: 0.8259236547600797

In [73]:
data['result'].value_counts()

result
0    133435
1    127485
Name: count, dtype: int64

In [69]:
dt.predict_proba([[1,8,16,0,1,0,1,1,0,1,0,0,119,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([[0., 1.]])

In [70]:
rf.predict_proba([[1,8,16,0,1,0,1,1,0,1,0,0,119,10]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([[0.21466667, 0.78533333]])

In [74]:
import joblib

# save Decision Tree
joblib.dump(dt, 'decision_tree_model.pkl')

# save Random Forest
joblib.dump(rf, 'random_forest_model.pkl')

['random_forest_model.pkl']